"""empty message

Revision ID: 32848f80facb
Revises: 8515255c6879
Create Date: 2022-08-01 16:11:49.934507

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "32848f80facb"
down_revision = "8515255c6879"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_book", sa.Column("quantity", sa.Integer(), nullable=False))
    op.drop_column("orders", "quantity")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("order_book", "quantity")
    # ### end Alembic commands ###
